### ISSUE TITLE
new Kutt.it API patch breaks `.list(<+50>)` functionality

### ISSUE THREAD

**Issue by MalekMFS** [RealAmirali/kutt.rb#2]
This problem occurs for users with +50 shortened links.
Now `k.list(<Greater than 50>)` returns only 50.

Hint to fix: **using Pagination**
`/api/url/geturls?isShortened=false&count=50&countAll=500&page=2&search=&`
This will return second 50 records (51th-100th) among 500 total shortened links.

**Comment by amirali** [comment]
Hi!  
Sorry, But I can't fix this for now  
I'm at school until summer  
Can you fix this by yourself?

**Comment by MalekMFS** [comment]
Hi bro,
I am very busy as well.
But as I will use it in the next few months, I will fix it and push to the repo.

**Comment by amirali** [comment]
Thank you so much <3
