### ISSUE TITLE
Documentation example does not work

### ISSUE THREAD

**Issue by agaelebe** [RealAmirali/kutt.rb#3]
In the docs we have:

`
k.submit("url", customurl="customurl", password="password", reuse=true)
`
But the reuse parameter should use a string and not a boolean.

If we use a boolean we get the following api error: 
> Illegal arguments: boolean, string

So maybe change the code to convert the boolean or just change the doc/example.

**Comment by MalekMFS** [comment]
Thank you.
You are right. Also, there was a problem with `submit` method optional arguments which if you only send `reuse = true` it will count it as `customurl`. I will make some changes to send hashes style as arguments, so optional arguements will work correctly.
